org: antalmanac
service: socspider
app: socspider

provider:
  name: aws
  runtime: python3.8
  region: us-west-1
  profile: socspider
  # Max timeout because this script runs for a while (several minutes)
  timeout: 900
  stage: dev
  environment:
    SOCSPIDER_TERM: ${param:SOCSPIDER_TERM}
    SOCSPIDER_MONGODB_URI: ${param:SOCSPIDER_MONGODB_URI}
    SOCSPIDER_MONGODB_USERNAME: ${param:SOCSPIDER_MONGODB_USERNAME}
    SOCSPIDER_MONGODB_PASSWORD: ${param:SOCSPIDER_MONGODB_PASSWORD}
    SOCSPIDER_DB_NAME: ${param:SOCSPIDER_DB_NAME}
    SOCSPIDER_CHUNKS_COLLECTION_NAME: ${param:SOCSPIDER_CHUNKS_COLLECTION_NAME}
    SOCSPIDER_ENROLLMENT_COLLECTION_NAME: ${param:SOCSPIDER_ENROLLMENT_COLLECTION_NAME}

plugins:
  - serverless-python-requirements

package:
 exclude:
   - node_modules/**
   - .vscode/**
   - exclude-me-dir/**
   - .env

functions:
  main:
    handler: main.main
    events:
    - schedule:
        rate: cron(0/20 * * * ? *)
        # Runs once a day at 11:00PM PST / 6:00AM UTC
        # rate: cron(0 6 * * ? *)
        enabled: true